/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author belie
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    
         
  
    DefaultTableModel model;
            
    public Home() {
        initComponents();
        homebookdetails();
        studentbookdetails();
    }
    
     //display book details
    public void homebookdetails(){
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_mgnt","root","");
           Statement st=con.createStatement();
           ResultSet rs= st.executeQuery("Select * from book_details");
           
           while (rs.next()){
               String bookId=rs.getString("book_id");
               String bookName=rs.getString("book_name");
               String author=rs.getString("author_name");
               int quantity= rs.getInt("quantity");
               
               Object[] obj={bookId,bookName,author,quantity};
               model=(DefaultTableModel)home_bookd.getModel();
               model.addRow(obj);
           }
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //insert book details
    
 
    //display student details
    public void studentbookdetails(){
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_mgnt","root","");
           Statement st=con.createStatement();
           ResultSet rs= st.executeQuery("Select * from student_details");
           
           while (rs.next()){
               int studentId =  rs.getInt("student_id");
               String studentName=rs.getString("name");
               String course=rs.getString("course");
               String section=rs.getString("section");
               
               Object[] obj={studentId,studentName,course,section};
               model=(DefaultTableModel)home_studentd.getModel();
               model.addRow(obj);
           }
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l2 = new javax.swing.JPanel();
        isl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        l9 = new javax.swing.JPanel();
        isl7 = new javax.swing.JLabel();
        l8 = new javax.swing.JPanel();
        isl6 = new javax.swing.JLabel();
        l7 = new javax.swing.JPanel();
        isl5 = new javax.swing.JLabel();
        l6 = new javax.swing.JPanel();
        isl3 = new javax.swing.JLabel();
        l4 = new javax.swing.JPanel();
        isl2 = new javax.swing.JLabel();
        l3 = new javax.swing.JPanel();
        isl1 = new javax.swing.JLabel();
        l5 = new javax.swing.JPanel();
        isl4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        home_bookd = new rojerusan.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        home_studentd = new rojerusan.RSTableMetro();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 17, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel3.setText(" Welcome to DigiLibrary ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 50));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 20, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 80));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setBackground(new java.awt.Color(51, 51, 51));
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l2MousePressed(evt);
            }
        });
        l2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl.setForeground(new java.awt.Color(255, 255, 255));
        isl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        isl.setText("Issue Books");
        isl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                islMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                islMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                islMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                islMousePressed(evt);
            }
        });
        l2.add(isl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 50));

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel10.setText("Home Page ");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 260, 70));

        l9.setBackground(new java.awt.Color(51, 51, 51));
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l9MousePressed(evt);
            }
        });
        l9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl7.setForeground(new java.awt.Color(255, 255, 255));
        isl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        isl7.setText("LogOut");
        isl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl7MousePressed(evt);
            }
        });
        l9.add(isl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 260, 50));

        l8.setBackground(new java.awt.Color(51, 51, 51));
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l8MousePressed(evt);
            }
        });
        l8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl6.setForeground(new java.awt.Color(255, 255, 255));
        isl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        isl6.setText("Records");
        isl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl6MousePressed(evt);
            }
        });
        l8.add(isl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 50));

        l7.setBackground(new java.awt.Color(51, 51, 51));
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l7MousePressed(evt);
            }
        });
        l7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl5.setForeground(new java.awt.Color(255, 255, 255));
        isl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        isl5.setText("Faulters List ");
        isl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl5MousePressed(evt);
            }
        });
        l7.add(isl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        l6.setBackground(new java.awt.Color(51, 51, 51));
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l6MousePressed(evt);
            }
        });
        l6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl3.setForeground(new java.awt.Color(255, 255, 255));
        isl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8-book-reading-24.png"))); // NOI18N
        isl3.setText("View Issued Books");
        isl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl3MousePressed(evt);
            }
        });
        l6.add(isl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 50));

        l4.setBackground(new java.awt.Color(51, 51, 51));
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l4MousePressed(evt);
            }
        });
        l4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl2.setForeground(new java.awt.Color(255, 255, 255));
        isl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        isl2.setText("Track Students");
        isl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl2MousePressed(evt);
            }
        });
        l4.add(isl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 50));

        l3.setBackground(new java.awt.Color(51, 51, 51));
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l3MousePressed(evt);
            }
        });
        l3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl1.setForeground(new java.awt.Color(255, 255, 255));
        isl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/11zon_resized (1).png"))); // NOI18N
        isl1.setText("Return Books");
        isl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl1MousePressed(evt);
            }
        });
        l3.add(isl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 50));

        l5.setBackground(new java.awt.Color(51, 51, 51));
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l5MousePressed(evt);
            }
        });
        l5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isl4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        isl4.setForeground(new java.awt.Color(255, 255, 255));
        isl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8-book-shelf-32.png"))); // NOI18N
        isl4.setText("Track Books");
        isl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isl4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isl4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isl4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isl4MousePressed(evt);
            }
        });
        l5.add(isl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel2.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 260, 630));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel15.setText("Book Details");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        home_bookd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Name", "Author", "Quantity"
            }
        ));
        home_bookd.setColorBackgoundHead(new java.awt.Color(153, 0, 0));
        home_bookd.setPreferredSize(new java.awt.Dimension(200, 600));
        jScrollPane1.setViewportView(home_bookd);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 480, 140));

        home_studentd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Name", "Course", "Section"
            }
        ));
        home_studentd.setColorBackgoundHead(new java.awt.Color(153, 0, 0));
        home_studentd.setPreferredSize(new java.awt.Dimension(200, 600));
        jScrollPane2.setViewportView(home_studentd);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 480, 140));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel20.setText("Student Details");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 650, 630));

        setSize(new java.awt.Dimension(912, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void l2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l2MousePressed

    private void l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseExited

        l2.setBackground(new Color(51, 51, 51));

        // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseExited

    private void l2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseEntered

        l2.setBackground(new Color(153, 0, 0));

        // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseEntered

    private void islMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_islMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_islMousePressed

    private void islMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_islMouseExited
l2.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_islMouseExited

    private void islMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_islMouseEntered
l2.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_islMouseEntered

    private void islMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_islMouseClicked
        IssueBooks isbpage = new IssueBooks();
        isbpage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_islMouseClicked

    private void isl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl1MouseClicked
        ReturnBooks rsbpage = new ReturnBooks();
        rsbpage.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_isl1MouseClicked

    private void isl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl1MouseEntered
l3.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl1MouseEntered

    private void isl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl1MouseExited
l3.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl1MouseExited

    private void isl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl1MousePressed

    private void l3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseEntered
 l3.setBackground(new Color(153, 0, 0));
   
        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseEntered

    private void l3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseExited
       
   l3.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseExited

    private void l3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l3MousePressed

    private void isl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl2MouseClicked
        TrackStudents tsbpage = new TrackStudents();
        tsbpage.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_isl2MouseClicked

    private void isl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl2MouseEntered
l4.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl2MouseEntered

    private void isl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl2MouseExited
l4.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl2MouseExited

    private void isl2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl2MousePressed

    private void l4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseEntered
 l4.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseEntered

    private void l4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseExited
l4.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseExited

    private void l4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l4MousePressed

    private void isl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl3MouseClicked
   ViewIssuedBooks visbpage = new ViewIssuedBooks();
        visbpage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_isl3MouseClicked

    private void isl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl3MouseEntered
l6.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl3MouseEntered

    private void isl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl3MouseExited
l6.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl3MouseExited

    private void isl3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl3MousePressed

    private void l6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseEntered
 l6.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseEntered

    private void l6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseExited
l6.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseExited

    private void l6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l6MousePressed

    private void isl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl4MouseClicked
        TrackBooks trbpage = new TrackBooks();
        trbpage.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_isl4MouseClicked

    private void isl4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl4MouseEntered
l5.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl4MouseEntered

    private void isl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl4MouseExited
l5.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl4MouseExited

    private void isl4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl4MousePressed

    private void l5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseEntered
 l5.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_l5MouseEntered

    private void l5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseExited
l5.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l5MouseExited

    private void l5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l5MousePressed

    private void isl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl5MouseClicked
        FaulterList flbpage = new FaulterList();
        flbpage.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_isl5MouseClicked

    private void isl5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl5MouseEntered
l7.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl5MouseEntered

    private void isl5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl5MouseExited
l7.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl5MouseExited

    private void isl5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl5MousePressed

    private void l7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseEntered
 l7.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_l7MouseEntered

    private void l7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseExited
l7.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l7MouseExited

    private void l7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l7MousePressed

    private void isl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl6MouseClicked
   BookRecords brpage = new BookRecords();
        brpage.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_isl6MouseClicked

    private void isl6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl6MouseEntered
l8.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl6MouseEntered

    private void isl6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl6MouseExited
l8.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl6MouseExited

    private void isl6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl6MousePressed

    private void l8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseEntered
 l8.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_l8MouseEntered

    private void l8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseExited
l8.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l8MouseExited

    private void l8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l8MousePressed

    private void isl7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl7MouseClicked
        ChangePassword lbpage = new ChangePassword();
        lbpage.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_isl7MouseClicked

    private void isl7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl7MouseEntered
l9.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl7MouseEntered

    private void isl7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl7MouseExited
l9.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_isl7MouseExited

    private void isl7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isl7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isl7MousePressed

    private void l9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseEntered
 l9.setBackground(new Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_l9MouseEntered

    private void l9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseExited
l9.setBackground(new Color(51, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_l9MouseExited

    private void l9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_l9MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro home_bookd;
    private rojerusan.RSTableMetro home_studentd;
    private javax.swing.JLabel isl;
    private javax.swing.JLabel isl1;
    private javax.swing.JLabel isl2;
    private javax.swing.JLabel isl3;
    private javax.swing.JLabel isl4;
    private javax.swing.JLabel isl5;
    private javax.swing.JLabel isl6;
    private javax.swing.JLabel isl7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel l2;
    private javax.swing.JPanel l3;
    private javax.swing.JPanel l4;
    private javax.swing.JPanel l5;
    private javax.swing.JPanel l6;
    private javax.swing.JPanel l7;
    private javax.swing.JPanel l8;
    private javax.swing.JPanel l9;
    // End of variables declaration//GEN-END:variables
}
