 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author belie
 */
public class ViewIssuedBooks extends javax.swing.JFrame {

    /**
     * Creates new form IssueBooks
     */
    DefaultTableModel model;
    public ViewIssuedBooks() {
        initComponents();
        issuedetails_table();
    }

    
    public void issuedetails_table(){
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_mgnt","root","");
           Statement st=con.createStatement();
           ResultSet rs= st.executeQuery("Select * from issue_details where status = '"+"Pending"+"'");
           
           while (rs.next()){
                int id =  rs.getInt("id");
               String bookName=rs.getString("book_name");
               String studentName=rs.getString("student_name");
               String issueDate=rs.getString("issue_date");
               String dueDate=rs.getString("due_date");
               String status=rs.getString("status");
               
               Object[] obj={id,bookName,studentName,issueDate,dueDate,status};
               model=(DefaultTableModel)vi_bd.getModel();
               model.addRow(obj);
           }
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //for clr 
    public void clrTable(){
        DefaultTableModel model= (DefaultTableModel) vi_bd.getModel();
        model.setRowCount(0);
    }
    
    //taking records from date input
    public void search() throws ParseException{
        Date issueddate = id_issuedate.getDate();
         Date returneddate = id_returndate.getDate();
        long l1= issueddate.getTime();
        long l2=returneddate.getTime();

        java.sql.Date frmdate = new java.sql.Date(l1);
        java.sql.Date todate = new java.sql.Date(l2);
        
        try{
           Connection con=DBconnection.getConnection();
           String sql="Select * from issue_details where status = '"+"Pending"+"' and issue_date BETWEEN ? and ?";
           PreparedStatement pst=con.prepareStatement(sql);
     
           pst.setDate(1, frmdate);
           pst.setDate(2, todate);
           ResultSet rs= pst.executeQuery();
           
           
             while(rs.next()){
               
               String id = rs.getString("id");
               String bookName = rs.getString("book_name");
               String studentName = rs.getString("student_name");
               String issueDate = rs.getString("issue_date");
               String dueDate= rs.getString("due_date");
               String status= rs.getString("status");
            
               Object[] obj={id,bookName,studentName,issueDate,dueDate,status};
               model=(DefaultTableModel)vi_bd.getModel();
               model.addRow(obj);
              
             }    
          
        }catch(Exception e){ 
           e.printStackTrace();
        }
    }
     
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        b_id = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_name = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        b_aname = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        b_qty = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle5 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle6 = new rojerusan.RSMaterialButtonCircle();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        b_id1 = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        b_name1 = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        b_aname1 = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        b_qty1 = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle7 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle8 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle9 = new rojerusan.RSMaterialButtonCircle();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        s_id = new app.bolivia.swing.JCTextField();
        jLabel24 = new javax.swing.JLabel();
        s_name = new app.bolivia.swing.JCTextField();
        jLabel25 = new javax.swing.JLabel();
        s_course = new app.bolivia.swing.JCTextField();
        jLabel26 = new javax.swing.JLabel();
        s_section = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_studentd = new rojerusan.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        main_panel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        bid_invalid = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        isbtn = new rojerusan.RSMaterialButtonCircle();
        sid_invalid = new javax.swing.JLabel();
        id_returndate = new com.toedter.calendar.JDateChooser();
        id_issuedate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        vi_bd = new rojerusan.RSTableMetro();
        isbtn1 = new rojerusan.RSMaterialButtonCircle();

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Add Book");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, 70));

        b_id.setBackground(new java.awt.Color(153, 0, 0));
        b_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_id.setForeground(new java.awt.Color(255, 255, 255));
        b_id.setToolTipText("");
        b_id.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_id.setPhColor(new java.awt.Color(255, 255, 255));
        b_id.setPlaceholder("Enter Book Id");
        b_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_idFocusLost(evt);
            }
        });
        b_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_idActionPerformed(evt);
            }
        });
        jPanel1.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book Id ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 60));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Book Name ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 60));

        b_name.setBackground(new java.awt.Color(153, 0, 0));
        b_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_name.setForeground(new java.awt.Color(255, 255, 255));
        b_name.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_name.setPhColor(new java.awt.Color(255, 255, 255));
        b_name.setPlaceholder("Enter Book Name");
        b_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_nameFocusLost(evt);
            }
        });
        b_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nameActionPerformed(evt);
            }
        });
        jPanel1.add(b_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Author Name ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, 60));

        b_aname.setBackground(new java.awt.Color(153, 0, 0));
        b_aname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_aname.setForeground(new java.awt.Color(255, 255, 255));
        b_aname.setActionCommand("<Not Set>");
        b_aname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_aname.setPhColor(new java.awt.Color(255, 255, 255));
        b_aname.setPlaceholder("Enter Author Name");
        b_aname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_anameFocusLost(evt);
            }
        });
        b_aname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anameActionPerformed(evt);
            }
        });
        jPanel1.add(b_aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 100, 60));

        b_qty.setBackground(new java.awt.Color(153, 0, 0));
        b_qty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_qty.setForeground(new java.awt.Color(255, 255, 255));
        b_qty.setToolTipText("");
        b_qty.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_qty.setPhColor(new java.awt.Color(255, 255, 255));
        b_qty.setPlaceholder("Enter Quantity");
        b_qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_qtyFocusLost(evt);
            }
        });
        b_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_qtyActionPerformed(evt);
            }
        });
        jPanel1.add(b_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle4.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle4.setText("Delete");
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 220, 60));

        rSMaterialButtonCircle5.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle5.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle5.setText("Update");
        rSMaterialButtonCircle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 220, 60));

        rSMaterialButtonCircle6.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle6.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle6.setText("Add");
        rSMaterialButtonCircle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 220, 60));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 20, 50));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Add Book");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, 70));

        b_id1.setBackground(new java.awt.Color(153, 0, 0));
        b_id1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_id1.setForeground(new java.awt.Color(255, 255, 255));
        b_id1.setToolTipText("");
        b_id1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_id1.setPhColor(new java.awt.Color(255, 255, 255));
        b_id1.setPlaceholder("Enter Book Id");
        b_id1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_id1FocusLost(evt);
            }
        });
        b_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_id1ActionPerformed(evt);
            }
        });
        jPanel2.add(b_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Book Id ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 60));

        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Book Name ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 60));

        b_name1.setBackground(new java.awt.Color(153, 0, 0));
        b_name1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_name1.setForeground(new java.awt.Color(255, 255, 255));
        b_name1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_name1.setPhColor(new java.awt.Color(255, 255, 255));
        b_name1.setPlaceholder("Enter Book Name");
        b_name1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_name1FocusLost(evt);
            }
        });
        b_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_name1ActionPerformed(evt);
            }
        });
        jPanel2.add(b_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Author Name ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, 60));

        b_aname1.setBackground(new java.awt.Color(153, 0, 0));
        b_aname1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_aname1.setForeground(new java.awt.Color(255, 255, 255));
        b_aname1.setActionCommand("<Not Set>");
        b_aname1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_aname1.setPhColor(new java.awt.Color(255, 255, 255));
        b_aname1.setPlaceholder("Enter Author Name");
        b_aname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_aname1FocusLost(evt);
            }
        });
        b_aname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aname1ActionPerformed(evt);
            }
        });
        jPanel2.add(b_aname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quantity");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 100, 60));

        b_qty1.setBackground(new java.awt.Color(153, 0, 0));
        b_qty1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        b_qty1.setForeground(new java.awt.Color(255, 255, 255));
        b_qty1.setToolTipText("");
        b_qty1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        b_qty1.setPhColor(new java.awt.Color(255, 255, 255));
        b_qty1.setPlaceholder("Enter Quantity");
        b_qty1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b_qty1FocusLost(evt);
            }
        });
        b_qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_qty1ActionPerformed(evt);
            }
        });
        jPanel2.add(b_qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        rSMaterialButtonCircle7.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle7.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle7.setText("Delete");
        rSMaterialButtonCircle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle7ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 220, 60));

        rSMaterialButtonCircle8.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle8.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle8.setText("Update");
        rSMaterialButtonCircle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle8ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 220, 60));

        rSMaterialButtonCircle9.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle9.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle9.setText("Add");
        rSMaterialButtonCircle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle9ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 220, 60));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 20, 50));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Add Students");

        jLabel23.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Student Id ");

        s_id.setBackground(new java.awt.Color(153, 0, 0));
        s_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        s_id.setForeground(new java.awt.Color(255, 255, 255));
        s_id.setToolTipText("");
        s_id.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        s_id.setPhColor(new java.awt.Color(255, 255, 255));
        s_id.setPlaceholder("Enter Student Id");
        s_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                s_idFocusLost(evt);
            }
        });
        s_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_idActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Student Name ");

        s_name.setBackground(new java.awt.Color(153, 0, 0));
        s_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        s_name.setForeground(new java.awt.Color(255, 255, 255));
        s_name.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        s_name.setPhColor(new java.awt.Color(255, 255, 255));
        s_name.setPlaceholder("Enter Student Name");
        s_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                s_nameFocusLost(evt);
            }
        });
        s_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_nameActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Course");

        s_course.setBackground(new java.awt.Color(153, 0, 0));
        s_course.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        s_course.setForeground(new java.awt.Color(255, 255, 255));
        s_course.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        s_course.setPhColor(new java.awt.Color(255, 255, 255));
        s_course.setPlaceholder("Enter Student Name");
        s_course.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                s_courseFocusLost(evt);
            }
        });
        s_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_courseActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Section");

        s_section.setBackground(new java.awt.Color(153, 0, 0));
        s_section.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        s_section.setForeground(new java.awt.Color(255, 255, 255));
        s_section.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        s_section.setPhColor(new java.awt.Color(255, 255, 255));
        s_section.setPlaceholder("Enter Student Name");
        s_section.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                s_sectionFocusLost(evt);
            }
        });
        s_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_sectionActionPerformed(evt);
            }
        });

        tb_studentd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Name", "Course", "Section"
            }
        ));
        tb_studentd.setColorBackgoundHead(new java.awt.Color(153, 0, 0));
        tb_studentd.setPreferredSize(new java.awt.Dimension(200, 600));
        tb_studentd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_studentdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_studentd);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 0, 0));
        jLabel33.setText("ISSUED BOOKS DETAILS");
        main_panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 450, 70));

        jLabel21.setBackground(new java.awt.Color(153, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 0));
        jLabel21.setText("X");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        main_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 20, 50));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("<");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        main_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        jLabel38.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 0));
        jLabel38.setText("Issue Date ");
        main_panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, 30));

        bid_invalid.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        bid_invalid.setForeground(new java.awt.Color(153, 0, 0));
        main_panel.add(bid_invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 140, 30));

        jLabel41.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 0, 0));
        jLabel41.setText("Return Date");
        main_panel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 140, 30));

        isbtn.setBackground(new java.awt.Color(153, 0, 0));
        isbtn.setText("ALL");
        isbtn.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        isbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbtnActionPerformed(evt);
            }
        });
        main_panel.add(isbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 210, 60));

        sid_invalid.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        sid_invalid.setForeground(new java.awt.Color(153, 0, 0));
        main_panel.add(sid_invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 140, 30));

        id_returndate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        id_returndate.setForeground(new java.awt.Color(153, 0, 0));
        id_returndate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                id_returndateComponentResized(evt);
            }
        });
        main_panel.add(id_returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 200, 40));

        id_issuedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        id_issuedate.setForeground(new java.awt.Color(153, 0, 0));
        id_issuedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                id_issuedateFocusLost(evt);
            }
        });
        id_issuedate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                id_issuedateComponentResized(evt);
            }
        });
        main_panel.add(id_issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 200, 40));

        vi_bd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        vi_bd.setColorBackgoundHead(new java.awt.Color(153, 0, 0));
        vi_bd.setPreferredSize(new java.awt.Dimension(200, 600));
        vi_bd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vi_bdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vi_bd);

        main_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 800, 280));

        isbtn1.setBackground(new java.awt.Color(153, 0, 0));
        isbtn1.setText("SEARCH");
        isbtn1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        isbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbtn1ActionPerformed(evt);
            }
        });
        main_panel.add(isbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 210, 60));

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 810));

        setSize(new java.awt.Dimension(1044, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_idFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_b_idFocusLost

    private void b_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_idActionPerformed

    private void b_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_b_nameFocusLost

    private void b_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_nameActionPerformed

    private void b_anameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_anameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_b_anameFocusLost

    private void b_anameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_anameActionPerformed

    private void b_qtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_qtyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_b_qtyFocusLost

    private void b_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_qtyActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void rSMaterialButtonCircle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle5ActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle5ActionPerformed

    private void rSMaterialButtonCircle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle6ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle6ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void b_id1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_id1FocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_b_id1FocusLost

    private void b_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_id1ActionPerformed

    private void b_name1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_name1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_b_name1FocusLost

    private void b_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_name1ActionPerformed

    private void b_aname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_aname1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_b_aname1FocusLost

    private void b_aname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_aname1ActionPerformed

    private void b_qty1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_qty1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_b_qty1FocusLost

    private void b_qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_qty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_qty1ActionPerformed

    private void rSMaterialButtonCircle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle7ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle7ActionPerformed

    private void rSMaterialButtonCircle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle8ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle8ActionPerformed

    private void rSMaterialButtonCircle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle9ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle9ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void s_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s_idFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_s_idFocusLost

    private void s_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_idActionPerformed

    private void s_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nameFocusLost

    private void s_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nameActionPerformed

    private void s_courseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s_courseFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s_courseFocusLost

    private void s_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_courseActionPerformed

    private void s_sectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s_sectionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s_sectionFocusLost

    private void s_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_sectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_sectionActionPerformed

    private void tb_studentdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_studentdMouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_tb_studentdMouseClicked

    private void id_issuedateComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_id_issuedateComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_id_issuedateComponentResized

    private void id_issuedateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_issuedateFocusLost

    }//GEN-LAST:event_id_issuedateFocusLost

    private void id_returndateComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_id_returndateComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_id_returndateComponentResized

    private void isbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbtnActionPerformed
  
            clrTable();
            issuedetails_table();
        
    }//GEN-LAST:event_isbtnActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Home hpage = new Home();
        hpage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void vi_bdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vi_bdMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_vi_bdMouseClicked

    private void isbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbtn1ActionPerformed

        
            clrTable();
        try {
            search();
        } catch (ParseException ex) {
            Logger.getLogger(ViewIssuedBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          
    }//GEN-LAST:event_isbtn1ActionPerformed

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewIssuedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField b_aname;
    private app.bolivia.swing.JCTextField b_aname1;
    private app.bolivia.swing.JCTextField b_id;
    private app.bolivia.swing.JCTextField b_id1;
    private app.bolivia.swing.JCTextField b_name;
    private app.bolivia.swing.JCTextField b_name1;
    private app.bolivia.swing.JCTextField b_qty;
    private app.bolivia.swing.JCTextField b_qty1;
    private javax.swing.JLabel bid_invalid;
    private com.toedter.calendar.JDateChooser id_issuedate;
    private com.toedter.calendar.JDateChooser id_returndate;
    private rojerusan.RSMaterialButtonCircle isbtn;
    private rojerusan.RSMaterialButtonCircle isbtn1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main_panel;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle5;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle6;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle7;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle8;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle9;
    private app.bolivia.swing.JCTextField s_course;
    private app.bolivia.swing.JCTextField s_id;
    private app.bolivia.swing.JCTextField s_name;
    private app.bolivia.swing.JCTextField s_section;
    private javax.swing.JLabel sid_invalid;
    private rojerusan.RSTableMetro tb_studentd;
    private rojerusan.RSTableMetro vi_bd;
    // End of variables declaration//GEN-END:variables
}
